package com.example.expensemate;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
  LinearLayout root, list; TextView balance, income, expense, rateText; SharedPreferences sp; double rate=15000;
  int blue=Color.rgb(37,99,235), green=Color.rgb(21,149,112), red=Color.rgb(216,74,74), ink=Color.rgb(23,32,42), muted=Color.rgb(107,114,128), bg=Color.rgb(246,247,251);
  int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
  GradientDrawable box(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTextColor(ink);b.setAllCaps(false);b.setBackground(box(Color.WHITE,16));b.setPadding(dp(12),0,dp(12),0);return b;}
  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);sp=getSharedPreferences("data",0);rate=Double.longBitsToDouble(sp.getLong("rate",Double.doubleToLongBits(15000))); build();}
  void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setPadding(dp(18),dp(14),dp(18),dp(8));root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(root);
    LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL); TextView title=tv("مصروفي",25,ink);title.setTypeface(null,1);top.addView(title,new LinearLayout.LayoutParams(0,dp(52),1));Button calc=btn("⌘  حاسبة");calc.setTextColor(blue);calc.setOnClickListener(v->calculator());top.addView(calc,new LinearLayout.LayoutParams(dp(105),dp(46)));root.addView(top);
    LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(18),dp(16),dp(18),dp(16));card.setBackground(box(ink,22));
    TextView l=tv("الرصيد الإجمالي التقريبي",13,Color.LTGRAY);card.addView(l);balance=tv("$0.00",31,Color.WHITE);balance.setTypeface(null,1);card.addView(balance,new LinearLayout.LayoutParams(-1,dp(46)));rateText=tv("سعر الصرف: 1$ = "+fmt(rate)+" ل.س",12,Color.LTGRAY);card.addView(rateText);root.addView(card,new LinearLayout.LayoutParams(-1,dp(132)));
    LinearLayout stats=new LinearLayout(this);stats.setPadding(0,dp(10),0,dp(8)); stats.addView(stat("الدخل",green),new LinearLayout.LayoutParams(0,dp(76),1));stats.addView(stat("المصروف",red),new LinearLayout.LayoutParams(0,dp(76),1));root.addView(stats);
    LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.CENTER);Button addI=btn("＋ دخل");addI.setTextColor(green);addI.setOnClickListener(v->addDialog(true));Button addE=btn("− مصروف");addE.setTextColor(red);addE.setOnClickListener(v->addDialog(false));Button settings=btn("⚙");settings.setOnClickListener(v->settings());actions.addView(addI,new LinearLayout.LayoutParams(0,dp(48),1));actions.addView(addE,new LinearLayout.LayoutParams(0,dp(48),1));actions.addView(settings,new LinearLayout.LayoutParams(dp(55),dp(48)));root.addView(actions);
    TextView h=tv("آخر العمليات",18,ink);h.setTypeface(null,1);h.setPadding(0,dp(12),0,dp(8));root.addView(h); ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));refresh(); }
  LinearLayout stat(String name,int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(14),dp(8),dp(14),dp(8));x.setBackground(box(Color.WHITE,16));TextView n=tv(name,12,muted);x.addView(n);TextView val=tv("$0.00",18,c);val.setTypeface(null,1);x.addView(val);if(name.equals("الدخل"))income=val;else expense=val;return x;}
  String fmt(double d){return new DecimalFormat("#,##0.##").format(d);}
  void refresh(){list.removeAllViews();String raw=sp.getString("items","");double inc=0,exp=0;String[] arr=raw.isEmpty()?new String[0]:raw.split("\\n",-1);for(int i=arr.length-1;i>=0;i--){if(arr[i].trim().isEmpty())continue;String[] p=arr[i].split("\\|",-1);if(p.length<5)continue;double a=Double.parseDouble(p[1]);boolean in=p[0].equals("I");String cur=p[2];double usd=cur.equals("USD")?a:a/rate;if(in)inc+=usd;else exp+=usd;list.addView(row(p,a,cur,in),new LinearLayout.LayoutParams(-1,dp(70)));}income.setText("$"+fmt(inc));expense.setText("$"+fmt(exp));balance.setText("$"+fmt(inc-exp));rateText.setText("سعر الصرف: 1$ = "+fmt(rate)+" ل.س");}
  View row(String[] p,double a,String cur,boolean in){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(12),dp(6),dp(12),dp(6));r.setBackground(box(Color.WHITE,16));TextView icon=tv(in?"＋":"−",25,in?green:red);icon.setGravity(Gravity.CENTER);r.addView(icon,new LinearLayout.LayoutParams(dp(42),dp(52)));LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);TextView d=tv(p[3],15,ink);d.setTypeface(null,1);mid.addView(d);mid.addView(tv(p[4],11,muted));r.addView(mid,new LinearLayout.LayoutParams(0,dp(55),1));TextView amount=tv((in?"+":"-")+fmt(a)+" "+cur,15,in?green:red);amount.setTypeface(null,1);r.addView(amount);r.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle("حذف العملية؟").setMessage(p[3]).setNegativeButton("إلغاء",null).setPositiveButton("حذف",(d,w)->delete(p[4],p[3],a,cur,in)).show();return true;});return r;}
  void delete(String date,String desc,double a,String cur,boolean in){String raw=sp.getString("items","");String target=(in?"I":"E")+"|"+a+"|"+cur+"|"+desc+"|"+date;StringBuilder b=new StringBuilder();for(String s:raw.split("\\n",-1))if(!s.equals(target)){if(b.length()>0)b.append('\n');b.append(s);}sp.edit().putString("items",b.toString()).apply();refresh();}
  void addDialog(boolean inc){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(20),0,dp(20),0);EditText amount=new EditText(this);amount.setHint("المبلغ");amount.setInputType(2|8192);x.addView(amount);EditText desc=new EditText(this);desc.setHint(inc?"مصدر الدخل":"على ماذا صرفت؟");x.addView(desc);Spinner cur=new Spinner(this);cur.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"USD","SYP"}));x.addView(cur);new AlertDialog.Builder(this).setTitle(inc?"إضافة دخل":"إضافة مصروف").setView(x).setNegativeButton("إلغاء",null).setPositiveButton("حفظ",(d,w)->{try{double a=Double.parseDouble(amount.getText().toString());String ds=desc.getText().toString().trim();if(ds.isEmpty())ds="بدون وصف";String date=new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(new Date());String line=(inc?"I":"E")+"|"+a+"|"+cur.getSelectedItem()+"|"+ds+"|"+date;String old=sp.getString("items","");sp.edit().putString("items",old.isEmpty()?line:old+"\n"+line).apply();refresh();}catch(Exception e){}}).show();amount.requestFocus();}
  void settings(){EditText e=new EditText(this);e.setInputType(2|8192);e.setText(fmt(rate));new AlertDialog.Builder(this).setTitle("سعر صرف الدولار").setMessage("الليرة السورية مقابل 1 دولار").setView(e).setNegativeButton("إلغاء",null).setPositiveButton("حفظ",(d,w)->{try{rate=Double.parseDouble(e.getText().toString().replace(",",""));sp.edit().putLong("rate",Double.doubleToLongBits(rate)).apply();refresh();}catch(Exception q){}}).show();}
  void calculator(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(18),0,dp(18),0);EditText e=new EditText(this);e.setHint("مثال: 120000 + 35 * 2");e.setTextSize(22);e.setGravity(Gravity.CENTER);x.addView(e,new LinearLayout.LayoutParams(-1,dp(60)));TextView result=tv("النتيجة: —",18,blue);result.setGravity(Gravity.CENTER);x.addView(result,new LinearLayout.LayoutParams(-1,dp(50)));new AlertDialog.Builder(this).setTitle("الحاسبة").setView(x).setNegativeButton("إغلاق",null).setPositiveButton("احسب",(d,w)->{result.setText("النتيجة: "+calc(e.getText().toString()));}).show();}
  String calc(String s){try{return fmt(eval(s.replace(" ","")));}catch(Exception e){return "صيغة غير صحيحة";}}
  double eval(String s){java.util.Stack<Double> nums=new java.util.Stack<>();java.util.Stack<Character> ops=new java.util.Stack<>();int i=0;while(i<s.length()){char c=s.charAt(i);if(Character.isDigit(c)||c=='.'){int j=i+1;while(j<s.length()&&(Character.isDigit(s.charAt(j))||s.charAt(j)=='.'))j++;nums.push(Double.parseDouble(s.substring(i,j)));i=j;continue;}if("+-*/".indexOf(c)>=0){while(!ops.empty()&&prec(ops.peek())>=prec(c))apply(nums,ops.pop());ops.push(c);i++;continue;}throw new RuntimeException();}while(!ops.empty())apply(nums,ops.pop());return nums.pop();}
  int prec(char c){return c=='+'||c=='-'?1:2;}void apply(java.util.Stack<Double> n,char o){double b=n.pop(),a=n.pop();n.push(o=='+'?a+b:o=='-'?a-b:o=='*'?a*b:a/b);}
}
